server:
  port: 8888
spring:  jpa:    hibernate:      ddl-auto: update
    generate-ddl: true      
  
  
  application:    name: user-service
    
  datasource:    url: jdbc:mysql://localhost:3306/user_profile
    username: root
    password: saurav
 
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    