server:
  port: 8989
  
spring:  
  application:
    name: address-service
<<<<<<< HEAD
  cloud:    config:      uri: http://localhost:8888 
 
=======
  cloud:
    config:
      uri: http://localhost:8888  
 
>>>>>>> cc46c1460cbd185d1f3cbd9551f5f9f9b94cd5e6
