server:
  port: 8989
  
spring:  
  application:
    name: address-service
  cloud:
    config:
      uri: http://localhost:8888 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 

