spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cts
    username: root
    password: dhiraj
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

