spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_profile
    username: root
    password: saurav 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true 

management:
  endpoints:
    web:
      exposure:
        include: refresh    
